sudo: required
language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.1
  - android-22
  - android-23
  - build-tools-23.0.1
  - android-28
  - build-tools-28.0.3
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_66e97601dc46_key -iv $encrypted_66e97601dc46_iv
  -in .keystore.enc -out .keystore -d
- touch $HOME/.android/repositories.cfg
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_script:
- curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
- sudo apt-get install -y nodejs
- node --version
- sudo npm install -g cordova
- curl https://install.meteor.com?release=1.4.1.2 | /bin/sh
- export PATH=$HOME/.meteor:$PATH
- meteor npm install
- cd $TRAVIS_BUILD_DIR/../
- git clone https://github.com/SharpAI/ApiServer.git
- git clone https://github.com/SharpAI/SharpAIPlugins.git
script:
- cd $TRAVIS_BUILD_DIR/
- meteor build $HOME --server=$API_SERVER_ADDRESS
services:
- mongodb
before_deploy:
- cp $TRAVIS_BUILD_DIR/.keystore $HOME
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 $HOME/android/release-unsigned.apk
  sharpai-mobile -keystore $HOME/.keystore -storepass $storepass -keypass $keypass
- "${ANDROID_HOME}/build-tools/28.0.3/zipalign 4 $HOME/android/release-unsigned.apk
  $HOME/android/sharpai-app.apk"
deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: "$HOME/android/sharpai-app.apk"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: lQW341zlQe19AotwPw6cTifFGFpNnHrIyzoPNkGKxTmsxU3NYay9EkpExUOvcxRjF+dAP5DA0B8KzQGQzCZGIIOH06ztJte1eKTb/joERq9WhQrIHNNk+KzKSBbpmquAxlpo+Q+PwPfK2KO7zCRG3gNKyQ/BPQ4gRMhISIQN/zbkaxoUR0hmAaV3Z3H+DfcD5iP/xkZ8yeJYya8spbEKq2T4Vv7sjkjNQFBVkkAy1MAbT6dZdjxytUrFrViOcL0vvUi9yiT3b3U/bIapkqILmSPydEUOLVSRfiGNK6BE4pmEneEjSL0uc94a/kP9d6tsaj4MncaowjABB+cKdQLJNBqqfRv5eySuswHk7ArDAKiC4dDRbUljXji2mO5hR0TPyUm9n43w9Q8a2BtbUCKRxbnf2KXjrciJS2pUqoYF4C9XESRSkvi5xHSKwhC66wi5SPu+WrwQ5c9DFVCaT0vQ9aYxi19MvZekhbjus2ssIiI6xyEVJb5TukXfLvgTGWtCK8myHSrI8KEJQyQ2FeguBepA3afQpHbXSoPAKoS6sXdYejLZ04C8hB9YaHOcrqhruqRXhEy7ysrDSFi/LpidUcDldXV7GWo1Ak/+qC/HHkp/fBSMtdmr01KmPIlchtBets+7KZR14El8UTyHZdhoiVCEnt4k3nsZ2NShhb0XRtM=
  - secure: nn9epx9j9CobAS7wejgUcyNxWD46W7u9opIhjiQgOV+9TUfCeyKPKtEmoNJdLsd+9MLhiUzQjjuV7+zkAsSh+/ycPxIvQfbUIVjSimATwK6NFuWod0DnQ89JFN4XHKXnumN/MUHpPqsJe6+hsdIg+dxkyhcbY1X3huB2Gywkxl96sOK6YvHq9SrdEteGjJhT4CPgtdGC/CSIslmvdSLYGUAgBed3qTOH81F5HSOMjH5JWhXt/ToJshzbVFONVhG3SnbDbFocx3tQ/gUB5kGGmFesMmFUP0CgYV/oAUgSTB/bfe0LBzJMF1YF/jfbYvlbTcplChBjy/JGU2N5WzbEnkIJ7MNG/SZ3MupWnMKIrjlwZB6Hu3KC5otWI93l0AOSeKy5ZhLFkWZQFyuZJSvGmiwa8c9AnfxomeD0e6QOqowiyzWhp0CROGn3RIHq3XuEHyv5vk7gCeN2BBBtmfqy2Gj8O6CPP0e+AOrF3m6i0j/XAFAq2e5DqhjAl+3KLyb49v8Sjldw7wl7I8E2k4rUSW0QAuP17Ha++qpBSG8t+As1pXsNpch7EKFdjlpwYPVK7Qwkqdgwdh83wsBWwaU47vWeQNU0WMlrZWwGc753kYXrYlTCRd8eebEGCxyPDb/cDnpjbnUmKnXGAj9zI8zOMgrM8HjRZGx/hNGr2pMijGE=
