sudo: required
language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.1
  - android-22
  - android-23
  - build-tools-23.0.1
  - android-28
  - build-tools-28.0.3
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_7aeb965aa3bd_key -iv $encrypted_7aeb965aa3bd_iv
  -in .keystore.enc -out .keystore -d
- touch $HOME/.android/repositories.cfg
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_script:
- curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
- sudo apt-get install -y nodejs
- node --version
- sudo npm install -g cordova
- curl https://install.meteor.com?release=1.4.1.2 | /bin/sh
- export PATH=$HOME/.meteor:$PATH
- meteor npm install
- cd $TRAVIS_BUILD_DIR/../
- git clone https://github.com/SharpAI/ApiServer
script:
- cd $TRAVIS_BUILD_DIR/hotShareMobile && ./cleanbuild.sh
- meteor build $HOME --server=$API_SERVER_ADDRESS
services:
- mongodb
before_deploy:
- cp $TRAVIS_BUILD_DIR/.keystore $HOME
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 $HOME/android/release-unsigned.apk
  sharpai-app -keystore $HOME/.keystore -storepass $storepass -keypass $keypass
- "${ANDROID_HOME}/build-tools/28.0.3/zipalign 4 $HOME/android/release-unsigned.apk
  $HOME/android/sharpai-app.apk"
deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: "$HOME/android/sharpai-app.apk"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: TzFw7l+MZwYLjpe8ly7pO+BDtsSX27k8jZLf92rym43X8Q2V4oKhqPhsnKekG5pECWaUFhq0wWfsgzp/bp1ScMqrAtK9ODBcGYWlT2R+jMEa+XoVC0yNs5T4yUc6TC/3+qKdTNj5+VcjrCtCJDvR+7C4wFB0YuTM0aIs/j6Nx/GkXFZKLhCG7koy4F35Xyrhvlu6EAwCN0UERmYX8xJEAbExJNEKu1HSzXPUU/07VOB+EAtxqeMDmPaRW3s0hXnIypRPJ0c+6TMdkUcxmTk+3i45oBwYA4Of1eU3SL5w3NuX+zYFpbC4qXRhD88IiAsgHzqXHaAl5nOXpy/r2xMvMfzVLKHBbazyD6dJIFmQD1ZAtdwf04/D0LolESguEDdq/F+AFFV3QXbmhbziQgCtbVjPwIxuAiCTpDlH35LPl2/LvfItKAASI67CgaMeuFD9L9RBnIDiSiD0g1J4xPH+7OFvmZc1uLiZl1d+3++RTVMiNXCveBNNZldxwtVjLVZNfUMcUK2spCKxQvQoEO6awCfesxDZe9VVgndVaq70OctTr60Id4gdm7ozTpkHGN0RTS5aNRUrrmsHDSR5vfYEgXc6M+vxMjMpV/6B3tb/EFOZp8hSptPjhkU7GyUgjX0YD8WzdctlNT3n9gt3IvM053q+iejC0Udhl+bX50rpJL0=
  - secure: Piq4s+W1lRvHmM6XQg59gLgBW+qpZAEPgtv2Bjd8q3QyE0t3ihrHIvgb4nk9GrFbofXnYnLc1XE/iPxic5DOk+9hb6TQK8lSjZV/pHuKW42FengzQ17ccEbtW9LGm0SNtnO03YDFcDDTIfx8DyXIrlp63lXZFHagCFTr0t7+EH4YcoyMkRvKA4BI+Dvf+lHCakJvtv2Qah8PjXulv3ZCo+LlWqjMCtxbFvcas+v0rj25TEFvuJQPC66IbrxiwEwmhZMr9/f5MzKvV0gzkq9yGGyl3ZQRb5EyMB/FMPCYvpW7M+Qx3AOifLCqppdBTMYon77uZNDcuREyP1uF6KzkXcvvIHWlqe7lkbduK5eLaacUtTl7c5IPivcfKF+2be+VQTV4pTEfHOin/1QGhn6vsEISs/79/ukLRHb4vkP7H86BMAZbbTLeB1A7JESkIc57jmma5ClLS/RcCh/tKL6StCplxOEPeW1TDnUfNSQx3TpC8KcbV15sl2OxI+Ppce77dTP6Uy4CcEhV01MgPnWTBRoVHbaw/XDFvqzJ4mhM7vfXVHHSjo1xKom1czSscwfea31Pj5cQ81jN8FdfYN3Sin0jGQpQKv05eHNgrY7Uy3E7rTz7IFvd+ngZR6yXHqJH4TldcYP+wj1zsQhTswvrT1fvptb8jytqMDKoEtmyrcw=
